### ISSUE TITLE
Update `.github/workflows/` Files to Use Secrets Instead of Credentials

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#817]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
`4.1.1+portage-4.1.0-uat-5`

**Details:**
- DMP Assistant favours using secrets over credentials. However, both `.github/workflows/postgres.yml` and `.github/workflows/mysql2.yml` include steps that entail the setup of credentials.

e.g. `.github/workflows/postgres.yml`
```yml
    # Stub out the Rails credentials file so that we can start the Rails app
    - name: 'Setup Credentials'
      run: |
        # generate a default credential file and key
        EDITOR='echo "$(cat config/credentials.yml.postgresql)" >' bundle exec rails credentials:edit
```
To better reflect the behaviour of DMP Assistant, and to give us more confidence in our tests, these workflows/ files should be updated to use secrets instead of credentials.
